//! Embedded templates for generating WASM entry crates.
//!
//! Each template is a function that takes agent/path parameters and
//! returns the complete file content as a `String`.

// ── wasip2 templates ─────────────────────────────────────────────────────────

fn toml_path(path: &str) -> String {
    path
        .strip_prefix(r"\\?\")
        .unwrap_or(path)
        .replace('\\', "/")
}

pub fn wasip2_cargo_toml(
    agent_name: &str,
    agent_path: &str,
) -> String {
    // Using the agent_name with -wasip2 suffix as the crate name
    let crate_name = format!("{agent_name}_wasip2_entry");
    let agent_path = toml_path(agent_path);
    format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
{agent_name} = {{ path = "{agent_path}", default-features = false }}
remi-agentloop = {{ git = "https://github.com/another-s347/remi-agentloop.git", default-features = false }}
remi-agentloop-macros = {{ git = "https://github.com/another-s347/remi-agentloop.git" }}
wit-bindgen = "0.53"
futures = "0.3"
async-stream = "0.3"
serde_json = "1"
"#
    )
}

pub fn wasip2_lib_rs(agent_name: &str, entry_fn: &str) -> String {
    // Convert crate name (kebab-case) to Rust identifier (snake_case)
    let agent_mod = agent_name.replace('-', "_");
    format!(
        r#"//! Auto-generated wasip2 entry crate for `{agent_name}`.
//!
//! Generated by `remi build --targets wasip2`.
//! Do not edit — regenerate by running the build command again.

#![allow(unused)]

use futures::{{Stream, StreamExt}};
use remi_agentloop::http::{{HttpStreamingResponse, HttpTransport, HttpTransportError}};
use remi_agentloop::prelude::*;
use remi_agentloop::protocol::ProtocolEvent;
use std::pin::Pin;

// ── WIT bindings ──────────────────────────────────────────────────────────────

wit_bindgen::generate!({{
    inline: "
        package remi:agentloop;

        interface http-transport {{
            resource response-body {{
                next-chunk: func() -> result<option<list<u8>>, string>;
            }}

            post-streaming: func(
                url: string,
                headers: list<tuple<string, string>>,
                body: list<u8>,
            ) -> result<tuple<u16, response-body>, string>;
        }}

        interface agent {{
            resource event-stream {{
                next: func() -> option<string>;
            }}
            chat: func(input-json: string) -> result<event-stream, string>;
        }}

        world agent-world {{
            import http-transport;
            export agent;
        }}
    ",
}});

// ── WitHttpTransport ──────────────────────────────────────────────────────────

#[derive(Clone)]
struct WitHttpTransport;

impl HttpTransport for WitHttpTransport {{
    fn post_streaming(
        &self,
        url: String,
        headers: Vec<(String, String)>,
        body: Vec<u8>,
    ) -> impl std::future::Future<Output = Result<HttpStreamingResponse, HttpTransportError>>
    {{
        async move {{
            let (status, response_body) =
                remi::agentloop::http_transport::post_streaming(&url, &headers, &body)
                    .map_err(|e| HttpTransportError::new(e))?;

            let stream = futures::stream::unfold(response_body, |body| async move {{
                match body.next_chunk() {{
                    Ok(Some(chunk)) => Some((Ok(chunk), body)),
                    Ok(None) => None,
                    Err(e) => Some((Err(HttpTransportError::new(e)), body)),
                }}
            }});

            Ok(HttpStreamingResponse {{
                status,
                headers: Vec::new(),
                body: Box::pin(stream),
            }})
        }}
    }}
}}

// ── WIT export ────────────────────────────────────────────────────────────────

pub struct RemiEventStream {{
    stream: std::cell::RefCell<Pin<Box<dyn Stream<Item = String>>>>,
}}

impl exports::remi::agentloop::agent::GuestEventStream for RemiEventStream {{
    fn next(&self) -> Option<String> {{
        let mut stream = self.stream.borrow_mut();
        futures::executor::block_on(stream.as_mut().next())
    }}
}}

struct AgentExport;

impl exports::remi::agentloop::agent::Guest for AgentExport {{
    type EventStream = RemiEventStream;

    fn chat(
        input_json: String,
    ) -> Result<exports::remi::agentloop::agent::EventStream, String> {{
        let input: LoopInput =
            serde_json::from_str(&input_json).map_err(|e| e.to_string())?;

        let (api_key, base_url, model) = extract_config(&input);

        let mut oai = OpenAIClient::with_transport(WitHttpTransport, &api_key);
        if !base_url.is_empty() {{
            oai = oai.with_base_url(&base_url);
        }}
        if !model.is_empty() {{
            oai = oai.with_model(&model);
        }}

        let agent = {agent_mod}::{entry_fn}(oai);

        let event_stream = async_stream::stream! {{
            match agent.chat(input).await {{
                Ok(inner) => {{
                    futures::pin_mut!(inner);
                    while let Some(event) = inner.next().await {{
                        let proto: ProtocolEvent = event.into();
                        yield serde_json::to_string(&proto)
                            .expect("ProtocolEvent serialization failed");
                    }}
                }}
                Err(e) => {{
                    let proto: ProtocolEvent = AgentEvent::Error(e).into();
                    yield serde_json::to_string(&proto)
                        .expect("ProtocolEvent serialization failed");
                }}
            }}
        }};

        Ok(exports::remi::agentloop::agent::EventStream::new(
            RemiEventStream {{
                stream: std::cell::RefCell::new(Box::pin(event_stream)),
            }},
        ))
    }}
}}

export!(AgentExport);

// ── Helpers ──────────────────────────────────────────────────────────────────

fn extract_config(input: &LoopInput) -> (String, String, String) {{
    let meta = match input {{
        LoopInput::Start {{ metadata, .. }} => metadata.as_ref(),
        LoopInput::Resume {{ state, .. }} => state.config.metadata.as_ref(),
        LoopInput::Cancel {{ state }} => state.config.metadata.as_ref(),
    }};

    let empty = serde_json::Value::Null;
    let meta = meta.unwrap_or(&empty);

    let api_key = meta["api_key"].as_str().unwrap_or("").to_string();
    let base_url = meta["base_url"].as_str().unwrap_or("").to_string();
    let model = meta["model"].as_str().unwrap_or("").to_string();

    (api_key, base_url, model)
}}
"#
    )
}

// ── web (browser) templates ──────────────────────────────────────────────────

pub fn web_cargo_toml(
    agent_name: &str,
    agent_path: &str,
) -> String {
    let crate_name = format!("{agent_name}-web-entry");
    let agent_path = toml_path(agent_path);
    format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
{agent_name} = {{ path = "{agent_path}", default-features = false }}
remi-agentloop = {{ git = "https://github.com/another-s347/remi-agentloop.git", default-features = false }}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = {{ version = "0.3", features = [
    "Headers",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Window",
    "ReadableStream",
    "ReadableStreamDefaultReader",
] }}
futures = "0.3"
async-stream = "0.3"
serde_json = "1"
uuid = {{ version = "1", features = ["v4", "js"] }}
getrandom = {{ version = "0.3", features = ["wasm_js"] }}
console_error_panic_hook = "0.1"
"#
    )
}

pub fn web_lib_rs(agent_name: &str, entry_fn: &str) -> String {
    let agent_mod = agent_name.replace('-', "_");
    format!(
        r#"//! Auto-generated browser WASM entry crate for `{agent_name}`.
//!
//! Generated by `remi build --targets web`.
//! Do not edit — regenerate by running the build command again.

use futures::{{Stream, StreamExt}};
use remi_agentloop::http::{{HttpStreamingResponse, HttpTransport, HttpTransportError}};
use remi_agentloop::prelude::*;
use remi_agentloop::protocol::ProtocolEvent;
use std::pin::Pin;
use wasm_bindgen::prelude::*;
use wasm_bindgen_futures::JsFuture;

// ── FetchTransport ───────────────────────────────────────────────────────────

#[derive(Clone)]
struct FetchTransport;

impl HttpTransport for FetchTransport {{
    fn post_streaming(
        &self,
        url: String,
        headers: Vec<(String, String)>,
        body: Vec<u8>,
    ) -> impl std::future::Future<Output = Result<HttpStreamingResponse, HttpTransportError>>
    {{
        async move {{
            let window = web_sys::window()
                .ok_or_else(|| HttpTransportError::new("no global window"))?;

            let js_headers = web_sys::Headers::new()
                .map_err(|e| HttpTransportError::new(format!("{{e:?}}")))?;
            for (k, v) in &headers {{
                js_headers
                    .set(k, v)
                    .map_err(|e| HttpTransportError::new(format!("{{e:?}}")))?;
            }}

            let opts = web_sys::RequestInit::new();
            opts.set_method("POST");
            opts.set_headers(&js_headers);

            let body_array = js_sys::Uint8Array::from(body.as_slice());
            opts.set_body(&body_array.into());

            let request = web_sys::Request::new_with_str_and_init(&url, &opts)
                .map_err(|e| HttpTransportError::new(format!("{{e:?}}")))?;

            let resp_value = JsFuture::from(window.fetch_with_request(&request))
                .await
                .map_err(|e| HttpTransportError::new(format!("fetch error: {{e:?}}")))?;

            let resp: web_sys::Response = resp_value
                .dyn_into()
                .map_err(|e| HttpTransportError::new(format!("{{e:?}}")))?;

            let status = resp.status();

            let readable_stream = resp
                .body()
                .ok_or_else(|| HttpTransportError::new("response has no body"))?;

            let reader = readable_stream
                .get_reader()
                .dyn_into::<web_sys::ReadableStreamDefaultReader>()
                .map_err(|e| HttpTransportError::new(format!("{{e:?}}")))?;

            let body_stream = futures::stream::unfold(reader, |reader| async move {{
                let result = JsFuture::from(reader.read()).await;
                match result {{
                    Ok(js_val) => {{
                        let done = js_sys::Reflect::get(&js_val, &JsValue::from_str("done"))
                            .unwrap_or(JsValue::TRUE)
                            .as_bool()
                            .unwrap_or(true);

                        if done {{
                            return None;
                        }}

                        let value =
                            js_sys::Reflect::get(&js_val, &JsValue::from_str("value")).ok()?;
                        let array = js_sys::Uint8Array::new(&value);
                        let chunk = array.to_vec();
                        Some((Ok(chunk), reader))
                    }}
                    Err(e) => Some((
                        Err(HttpTransportError::new(format!("read error: {{e:?}}"))),
                        reader,
                    )),
                }}
            }});

            Ok(HttpStreamingResponse {{
                status,
                headers: Vec::new(),
                body: Box::pin(body_stream),
            }})
        }}
    }}
}}

// ── wasm-bindgen exports ─────────────────────────────────────────────────────

#[wasm_bindgen]
pub struct EventStream {{
    stream: std::cell::RefCell<Pin<Box<dyn Stream<Item = String>>>>,
}}

#[wasm_bindgen]
impl EventStream {{
    pub async fn next(&self) -> JsValue {{
        let mut stream = self.stream.borrow_mut();
        match stream.as_mut().next().await {{
            Some(json) => JsValue::from_str(&json),
            None => JsValue::UNDEFINED,
        }}
    }}
}}

#[wasm_bindgen]
pub fn chat(input_json: &str) -> Result<EventStream, JsValue> {{
    console_error_panic_hook::set_once();

    let input: LoopInput = serde_json::from_str(input_json)
        .map_err(|e| JsValue::from_str(&format!("parse error: {{e}}")))?;

    let (api_key, base_url, model) = extract_config(&input);

    let mut oai = OpenAIClient::with_transport(FetchTransport, &api_key);
    if !base_url.is_empty() {{
        oai = oai.with_base_url(&base_url);
    }}
    if !model.is_empty() {{
        oai = oai.with_model(&model);
    }}

    let agent = {agent_mod}::{entry_fn}(oai);

    let event_stream = async_stream::stream! {{
        match agent.chat(input).await {{
            Ok(inner) => {{
                futures::pin_mut!(inner);
                while let Some(event) = inner.next().await {{
                    let proto: ProtocolEvent = event.into();
                    yield serde_json::to_string(&proto)
                        .expect("ProtocolEvent serialization failed");
                }}
            }}
            Err(e) => {{
                let proto: ProtocolEvent = AgentEvent::Error(e).into();
                yield serde_json::to_string(&proto)
                    .expect("ProtocolEvent serialization failed");
            }}
        }}
    }};

    Ok(EventStream {{
        stream: std::cell::RefCell::new(Box::pin(event_stream)),
    }})
}}

// ── Helpers ──────────────────────────────────────────────────────────────────

fn extract_config(input: &LoopInput) -> (String, String, String) {{
    let meta = match input {{
        LoopInput::Start {{ metadata, .. }} => metadata.as_ref(),
        LoopInput::Resume {{ state, .. }} => state.config.metadata.as_ref(),
        LoopInput::Cancel {{ state }} => state.config.metadata.as_ref(),
    }};

    let empty = serde_json::Value::Null;
    let meta = meta.unwrap_or(&empty);

    let api_key = meta["api_key"].as_str().unwrap_or("").to_string();
    let base_url = meta["base_url"].as_str().unwrap_or("").to_string();
    let model = meta["model"].as_str().unwrap_or("").to_string();

    (api_key, base_url, model)
}}
"#
    )
}
